name: Build libgodot
description: Build libgodot with the provided options.
inputs:
  bin:
    description: Path to the Godot binary.
    required: true
  platform:
    description: The libgodot platform to build.
    required: false
runs:
  using: "composite"
  steps:
    - name: Generate api.json
      shell: sh
      run: ${{ inputs.bin }} --no-window --audio-driver Dummy --gdnative-generate-json-api ./bin/api.json
      continue-on-error: true

    - name: Scons Build (debug)
      shell: sh
      run: scons --directory=modules/gdnative/binding p=${{ inputs.platform }} target=debug --jobs=2

    - name: Scons Build (release)
      shell: sh
      run: scons --directory=modules/gdnative/binding p=${{ inputs.platform }} target=release --jobs=2
