name: 🌐 Emscripten Builds
on:
  workflow_call:

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.3
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no
  EM_VERSION: 3.1.74

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-emscripten_builds
  cancel-in-progress: true

jobs:
  build-emscripten:
    runs-on: ubuntu-22.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes, threads_enabled=yes)
            cache-name: emscripten-editor
            target: release_debug
            tools: yes
            sconsflags: threads_enabled=yes

          - name: Template (target=release, tools=no)
            cache-name: emscripten-template
            target: release
            tools: no

    steps:
      - uses: actions/checkout@v4

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Emscripten SDK
        shell: bash
        run: |
          git clone https://github.com/emscripten-core/emsdk.git

          cd emsdk
          ./emsdk install ${{ env.EM_VERSION }}
          ./emsdk activate ${{ env.EM_VERSION }}
          source ./emsdk_env.sh

          EMSDK_PATH=$(pwd)
          echo "$EMSDK_PATH" >> $GITHUB_PATH
          echo "$EMSDK_PATH/upstream/emscripten" >> $GITHUB_PATH

      - name: Patch Emscripten SDK
        shell: bash
        run: |
          patch -d "emsdk/upstream/emscripten" -p1 < ".github/patches/emscripten-3.1.74-fix-crash-in-getifaddrs.patch"

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: emscripten
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

  deploy-web-editor:
    permissions:
      contents: read
      deployments: write
      pull-requests: write

    runs-on: ubuntu-22.04
    timeout-minutes: 10
    needs: build-emscripten
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: emscripten-editor
          path: "${{ runner.temp }}/emscripten-editor/"

      - name: Prepare dist
        shell: bash
        run: |
          mkdir web-editor-dist && cd $_
          7z x "${{ runner.temp }}/emscripten-editor/godot.emscripten.opt.tools.threads.zip"

      - name: Deploy to Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages@v3.2.2
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: web-editor-dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ (github.ref == 'refs/heads/master' && 'web-editor-production') || 'web-editor-preview' }}
