name: 📄 Push Checks
on:
  workflow_call:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-push_checks
  cancel-in-progress: true

jobs:
  push-checks:
    name: Push Checks (has-open-pr)
    runs-on: ubuntu-22.04
    outputs:
      has-open-pr: ${{ steps.check-prs.outputs.has-open-pr }}
    steps:
      - name: Check for open PRs
        id: check-prs
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const MAX_ATTEMPTS = 5;
            const INITIAL_DELAY = 2000;
            const BACKOFF_FACTOR = 2;
            let hasPR = false;

            for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
              try {
                const cacheBuster = Date.now();
                const { data: prs } = await github.rest.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open',
                  head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`,
                  headers: { 'If-None-Match': '' },
                  query: { _: cacheBuster }
                });

                if (prs.length > 0) {
                  hasPR = true;
                  console.log(`🔵 Found open PRs on attempt ${attempt}`);
                  break;
                }
              } catch (error) {
                if (error.status === 404) {
                  console.log(`🟡 Repo not found, assuming no PR`);
                } else {
                  console.log(`🟠 Attempt ${attempt} failed: ${error.message}`);
                }
              }

              if (!hasPR && attempt < MAX_ATTEMPTS) {
                const waitTime = INITIAL_DELAY * Math.pow(BACKOFF_FACTOR, attempt - 1);
                console.log(`🟣 No PR found, waiting ${waitTime}ms before retry...`);
                await new Promise(resolve => setTimeout(resolve, waitTime));
              }
            }

            core.setOutput('has-open-pr', hasPR ? 'true' : 'false');
            console.log(`🟢 Final result: has-open-pr=${hasPR}`);
