name: 🔗 GHA for the push
run-name: |
  ${{
    (github.ref == 'refs/heads/master' && format('🚀 Production | {0}', github.event.head_commit.message))
    || format('🧪 Testing | {0}', github.event.head_commit.message)
  }}

on: [push]

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-push_runner
  cancel-in-progress: true

jobs:
  push-checks:
    name: 📄 Push
    uses: ./.github/workflows/push_checks.yml

  static-checks:
    needs: push-checks
    name: 📊 Static
    if: ${{ github.ref == 'refs/heads/master' || needs.push-checks.outputs.has-open-pr == 'false' }}
    uses: ./.github/workflows/static_checks.yml

  windows-build:
    name: 🏁 Windows
    needs: static-checks
    uses: ./.github/workflows/windows_builds.yml

  emscripten-build:
    name: 🌐 Emscripten
    needs: static-checks
    uses: ./.github/workflows/emscripten_builds.yml

  deploy-web-editor:
    if: ${{ github.ref == 'refs/heads/master' }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: web-editor
      url: "${{ steps.deployment.outputs.page_url }}godot.tools.html"

    runs-on: ubuntu-22.04
    needs: emscripten-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
